### ISSUE TITLE
Node production improperly calculated.

### ISSUE THREAD

**Issue by Theod0reWu** [bcollazo/catanatron#263]
https://github.com/bcollazo/catanatron/blob/2ae972fb72ddcdf9c0793478647b9137f3b76b3c/catanatron_core/catanatron/models/map.py#L316

The node production for a spot that has two tiles with the same resource, will only have the production from one of those tiles.

**Comment by bcollazo** [comment]
Woah! This is a great find! Thank you so much for the contribution! Fixed in https://github.com/bcollazo/catanatron/pull/264 (merged to master).
