### ISSUE TITLE
Gym seems to be broken?

### ISSUE THREAD

**Issue by ChrisJWest** [bcollazo/catanatron#265]
Having issues with unpacking certain things when I try to just run the default example on the readme. I think it has to do with the change to gymnasium as well as the addition of "truncated". Would appreciate if you could look into it, thanks!

**Comment by bcollazo** [comment]
Hey, thanks for reporting!

Would it be possible for you to share the stacktrace that you are seeing? Are you using a particular RL Python library? If you can include the results of running `pip freeze` in your environment that would also be helpful!

I started cooking a Pull Request that I think might fix it: https://github.com/bcollazo/catanatron/pull/266. But not 100% it will fix your use case. With more details we might be able to make sure it works for you!

Thanks again for reporting!

**Comment by bcollazo** [comment]
Should have been fixed by https://github.com/bcollazo/catanatron/pull/266. If you see any issues feel free to reopen!
