### ISSUE TITLE
Implement returning all players points vs winner player colour

### ISSUE THREAD

**Issue by lpoblet** [bcollazo/catanatron#269]
I'm interested in generating player statistics randomly. It'd be much better for me to know the points of all players instead of the winner

**Comment by bcollazo** [comment]
Hello lpoblet, 

There is a state function called `get_actual_victory_points` (https://github.com/bcollazo/catanatron/blob/2a4f078ba17bd4d7916fea7dfa625e4ccb97e586/catanatron_core/catanatron/state_functions.py#L80) that you can call at the end of the game with the particular color you are interested in. You can also iterate over the colors in the game with `game.state.colors`.

This is similar to how the `StatisticsAccumulator` ([catanatron_experimental/cli/accumulators.py](https://github.com/bcollazo/catanatron/blob/2a4f078ba17bd4d7916fea7dfa625e4ccb97e586/catanatron_experimental/catanatron_experimental/cli/accumulators.py#L126C1-L128C57)) keeps track of several statistics and shows them at the end of a run when using the CLI. You could also register your own custom accumulator (https://github.com/bcollazo/catanatron/tree/master?tab=readme-ov-file#accumulators) depending on the need.

**Comment by bcollazo** [comment]
I believe the answer addresses comment. Closing. Happy to open if more people feel like there should be a change in the API (return value of `game.play()`).
