### ISSUE TITLE
docker-compose images are outdated

### ISSUE THREAD

**Issue by HassanJbara** [bcollazo/catanatron#273]
Running the docker-compose file to start the react server fails in the react-ui container due to this error: `The engine "node" is incompatible with this module. Expected version ">=16.0.0 <17.0.0". Got "15.5.0"`. I looked into the `bcollazo/catanatron-react-ui:latest` image and it seems like it indeed uses a wrong node version. Furthermore, the server image uses a wrong flask server file (`catanatron_server/server` instead of `catanatron_server/catanatron_server`).

### Suggested Solution

Either update the images or simply comment out the image option under the react-ui and server containers in docker-compose, forcing docker to build the images from the local dockerfiles instead.

**Comment by MuhammadFaizan005** [comment]
I got the same issue, Did you try the solution which you’ve suggested?

**Comment by HassanJbara** [comment]
> I got the same issue, Did you try the solution which you’ve suggested?

Yes. Both of the solutions I provided are valid and I will leave up to the maintainer what to implement, but you can simply comment out the image options.

**Comment by bcollazo** [comment]
Hey! Thanks for noting and investigating the solutions. Both look good to me! I haven't had much time recently to build and publish new images to DockerHub. In the meantime, feel free to submit a PR with the second solution of changing the README.md to make people build instead of pull the outdated ones from DockerHub. 👍

**Comment by MuhammadFaizan005** [comment]
> > I got the same issue, Did you try the solution which you’ve suggested?
> 
> Yes. Both of the solutions I provided are valid and I will leave up to the maintainer what to implement, but you can simply comment out the image options.

Thanks Bro this works absolutely fine turns out That docker was also causing issues on my side, I’ve reinstalled windows packages. It now runs perfectly.

**Comment by HassanJbara** [comment]
> Hey! Thanks for noting and investigating the solutions. Both look good to me! I haven't had much time recently to build and publish new images to DockerHub. In the meantime, feel free to submit a PR with the second solution of changing the README.md to make people build instead of pull the outdated ones from DockerHub. 👍

Hi, will create a PR when I have time. Can you please check the discussions? I think that is more important :)
