### ISSUE TITLE
Write test to ensure stealing largest army needs 1 more knight

### ISSUE THREAD

**Issue by bcollazo** [bcollazo/catanatron#61]
Not sure a player can steal "largest army" by just tie-ing the number of knights. Should need 1 more than current largest army holder. This issue asks to write a test to ensure the code deals with this correctly.

**Comment by pachewise** [comment]
How do you serialize state? I am wondering if, for this test, we can just start with a state where someone has largest army and someone is about to play a knight to tie the largest army.

**Comment by bcollazo** [comment]
We serialize the state to JSON using the code in `json.py`. The actual data structure that contains the state information is in the `state.py` file, and we have accessor functions to this class in `state_functions.py` (functional architecture adopted for speed).

Yeah, for sure that suggestion makes sense. Actually, just realized this is slightly covered by `test_largest_army_calculation_on_tie` on `test_algorithms.py`. There might be space for a more end-to-end version, but I think this is ok for now. Closing.
